# Generated by Django 5.1.3 on 2024-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.CharField(
                        choices=[
                            ("O", "Открытая привычка"),
                            ("P", "Приватная привычка"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="публичная/приватная",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название привычки"),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        verbose_name="Продолжительность в минутах"
                    ),
                ),
                (
                    "time_action",
                    models.TimeField(
                        max_length=25,
                        verbose_name="Время, когда надо выполнить привычку",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=100, verbose_name="Действие, которое надо сделать"
                    ),
                ),
                (
                    "prize",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Приятная-True/Полезная-False"
                    ),
                ),
                (
                    "last_performed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последнего выполнения"
                    ),
                ),
                (
                    "execution_interval_day",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Интервал выполнения (в днях)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активна/не активна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
